# BEGIN
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
# END
