# BEGIN
spring:
  datasource:
    url: jdbc:h2:file:./test
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
# END
